CREATE TABLE IF NOT EXISTS users
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(512)                             NOT NULL,
    email     VARCHAR(512)                             NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);